"""Golden snapshot regression test for Phase 11/12 status-summary functions.

The golden fixture at ``fixtures/snapshots/status-summaries-v1.json`` is
regenerated by rerunning the generator (``_collect_summaries``): import both
contract modules, collect every ``phaseNN*_status_summary`` function via
``inspect.getmembers`` that can be called with no arguments, plus the three
required-arg summaries ``_doctor`` invokes, each called with the same
canonical ``domain`` arguments ``_doctor`` uses. This test locks those
outputs against unintended change: if any function's return value drifts, the
snapshot comparison will fail and name the drifted phase.
"""

from __future__ import annotations

import inspect
import json
import unittest
from pathlib import Path

from somatic.safety import phase11_contracts, phase12_contracts
from somatic.safety.phase11_contracts import (
    PHASE11_DOCUMENT_DOMAIN,
    PHASE11_WIFI_CSI_RF_BOOTH_DOMAIN,
    phase11_dossier_lifecycle_status_summary,
    phase11_preflight_status_summary,
    phase11_review_record_status_summary,
)

FIXTURE = (
    Path(__file__).resolve().parents[1] / "fixtures" / "snapshots" / "status-summaries-v1.json"
)

# Same domains ``somatic.cli.main._doctor`` passes to the three required-arg
# summaries. Both are captured so the snapshot covers every doctor-invoked path.
DOCTOR_STATUS_DOMAINS = (
    PHASE11_DOCUMENT_DOMAIN,
    PHASE11_WIFI_CSI_RF_BOOTH_DOMAIN,
)

DOCTOR_REQUIRED_ARG_SUMMARIES = (
    ("phase11_preflight_status_summary", phase11_preflight_status_summary),
    ("phase11_dossier_lifecycle_status_summary", phase11_dossier_lifecycle_status_summary),
    ("phase11_review_record_status_summary", phase11_review_record_status_summary),
)

# 27 zero-arg summaries + 3 required-arg functions x 2 doctor domains.
EXPECTED_SNAPSHOT_COUNT = 33


def _doctor_invoked_key(name: str, domain: str) -> str:
    return f"{name}[{domain}]"


def _collect_summaries() -> dict:
    """Reconstruct the same dict the generator produces."""
    summaries: dict = {}
    for mod in (phase11_contracts, phase12_contracts):
        for name, func in inspect.getmembers(mod, inspect.isfunction):
            if name.startswith(("phase11", "phase12")) and name.endswith("_status_summary"):
                sig = inspect.signature(func)
                required = [
                    p
                    for p in sig.parameters.values()
                    if p.default is inspect.Parameter.empty
                    and p.kind
                    not in (inspect.Parameter.VAR_POSITIONAL, inspect.Parameter.VAR_KEYWORD)
                ]
                if required:
                    continue
                summaries[name] = func()
    for name, func in DOCTOR_REQUIRED_ARG_SUMMARIES:
        for domain in DOCTOR_STATUS_DOMAINS:
            summaries[_doctor_invoked_key(name, domain)] = func(domain=domain)
    return summaries


def regenerate_fixture() -> None:
    """Write ``_collect_summaries()`` to the golden fixture path."""

    payload = _collect_summaries()
    FIXTURE.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


class StatusSummarySnapshotTests(unittest.TestCase):
    """Status-summary outputs must match the golden snapshot exactly."""

    @classmethod
    def setUpClass(cls):
        cls.golden = json.loads(FIXTURE.read_text(encoding="utf-8"))

    def test_snapshot_matches_current_outputs(self):
        """Every status-summary function's return value must match the golden."""
        reconstructed = _collect_summaries()
        self.assertEqual(
            reconstructed,
            self.golden,
            "Status summary snapshot drift detected —"
            " regenerate the fixture if the change is intended.",
        )

    def test_snapshot_covers_true_count(self):
        """The golden snapshot must cover every collected doctor-invoked path."""
        self.assertEqual(len(self.golden), EXPECTED_SNAPSHOT_COUNT)
        for name, _func in DOCTOR_REQUIRED_ARG_SUMMARIES:
            for domain in DOCTOR_STATUS_DOMAINS:
                key = _doctor_invoked_key(name, domain)
                self.assertIn(key, self.golden)

    def test_cached_summaries_return_independent_copies(self):
        """Memoized builders must deepcopy so callers cannot poison the cache."""
        first = phase11_preflight_status_summary(domain=PHASE11_DOCUMENT_DOMAIN)
        first["domain"] = "mutated-by-caller"
        second = phase11_preflight_status_summary(domain=PHASE11_DOCUMENT_DOMAIN)
        self.assertEqual(second["domain"], PHASE11_DOCUMENT_DOMAIN)


if __name__ == "__main__":
    unittest.main()
