"""Memory lane scaffold for future local-first run and evidence memory."""

from .baseline import (
    BASELINE_CATEGORIES,
    BaselineComparison,
    BaselineGraph,
    BaselineMetric,
    BaselinePrivacyBoundary,
    BaselineWindow,
    PersonalProfile,
    baseline_status_counts,
    build_baseline_graph,
    build_personal_profile,
    compare_feature_set_to_baseline,
    load_fake_baseline_graph,
    load_fake_personal_profile,
)
from .intervention import (
    DISABLED_INTERVENTION_CATEGORIES,
    INTERVENTION_CATEGORIES,
    InterventionContext,
    InterventionTag,
    InterventionWindow,
    MockInterventionLedger,
    ResponseEvaluationPlan,
    build_intervention_context,
    build_intervention_tag,
    build_mock_intervention_ledger,
    build_response_evaluation_plan,
    load_fake_intervention_plan,
    load_fake_intervention_tag,
)
from .response_evaluation import (
    AWAY_FROM_BASELINE,
    RESPONSE_TREND_STATUSES,
    TOWARD_BASELINE,
    UNCHANGED,
    FollowUpObservationWindow,
    FollowUpSensorSnapshot,
    ResponseComparison,
    ResponseEvaluationSummary,
    build_follow_up_observation_window,
    build_follow_up_sensor_snapshot,
    build_response_comparison,
    build_response_evaluation_summary,
    load_fake_response_evaluation,
)

STATUS = "scaffolded"
LOCAL_FIRST_BY_DEFAULT = True


__all__ = [
    "BASELINE_CATEGORIES",
    "AWAY_FROM_BASELINE",
    "LOCAL_FIRST_BY_DEFAULT",
    "RESPONSE_TREND_STATUSES",
    "STATUS",
    "TOWARD_BASELINE",
    "UNCHANGED",
    "BaselineComparison",
    "BaselineGraph",
    "BaselineMetric",
    "BaselinePrivacyBoundary",
    "BaselineWindow",
    "DISABLED_INTERVENTION_CATEGORIES",
    "INTERVENTION_CATEGORIES",
    "InterventionContext",
    "InterventionTag",
    "InterventionWindow",
    "FollowUpObservationWindow",
    "FollowUpSensorSnapshot",
    "MockInterventionLedger",
    "PersonalProfile",
    "ResponseComparison",
    "ResponseEvaluationSummary",
    "ResponseEvaluationPlan",
    "baseline_status_counts",
    "build_baseline_graph",
    "build_follow_up_observation_window",
    "build_follow_up_sensor_snapshot",
    "build_intervention_context",
    "build_intervention_tag",
    "build_mock_intervention_ledger",
    "build_personal_profile",
    "build_response_comparison",
    "build_response_evaluation_summary",
    "build_response_evaluation_plan",
    "compare_feature_set_to_baseline",
    "load_fake_baseline_graph",
    "load_fake_intervention_plan",
    "load_fake_intervention_tag",
    "load_fake_personal_profile",
    "load_fake_response_evaluation",
]
